sat_incidents_db_filename: %CONFIGDIR%/sat_incidents.db
product2affected_entity_map:
  "IODC_.*":            ["41° E IODC", "MET-8"]
  ".*METEOSAT_.*":      ["0° SEVIRI LEVEL 1\\.5 IMAGE DATA", "MET-10"] 
  "METEOSATRSS_.*":     ["RSS SEVIRI LEVEL 1\\.5 IMAGE DATA", "MET-9"] 
  "Warnappbild_.*":     ["0° SEVIRI LEVEL 1\\.5 IMAGE DATA", "MET-10", "NWC SAF.*"] 
  "Fernsehbild_.*":     ["0° SEVIRI LEVEL 1\\.5 IMAGE DATA", "MET-10", "NWC SAF.*"] 
  "WCM_.*":             ["0° SEVIRI LEVEL 1\\.5 IMAGE DATA", "MET-10", "41° E IODC", "MET-8", "GOES13", "GOES15", "HIMAWARI-8"] 
